[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]

[tool.black]
target_version = ['py36']

[tool.pytest.ini_options]
addopts = "--doctest-modules"
testpaths = [
	"tests",
	"xdem"
]
