# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.14.dev14+g4c8c9fc.d20230904'
__version_tuple__ = version_tuple = (0, 0, 14, 'dev14', 'g4c8c9fc.d20230904')
