coregistration:
  process: true
  step_one:
    extra_information:
      subsample: 10000
    method: LZD
inputs:
  reference_elev:
    downsample: 1
    force_vcrs: null
    path_to_elev: ../../../xdem/example_data/Longyearbyen/data/DEM_2009_ref.tif
  sampling_grid: reference_elev
  to_be_aligned_elev:
    downsample: 1
    force_vcrs: null
    path_to_elev: ../../../xdem/example_data/Longyearbyen/data/DEM_1990.tif
    path_to_mask: ../../../xdem/example_data/Longyearbyen/data/glacier_mask/CryoClim_GAO_SJ_1990.shp
outputs:
  generate_pdf: true
  level: 1
  path: outputs_accuracy
statistics:
- median
- nmad
- validcount
