name: xdem-demo
channels:
  - conda-forge
dependencies:
  - pip
  - python>=3.8
  - jupyter
  - jupytext  # used to render example scripts as notebooks
  - numpy
  - matplotlib
  - geoutils
  - xdem
  # - pip:
  #     - git+https://github.com/GlacioHack/geoutils.git
  #     - git+https://github.com/GlacioHack/xdem.git