name: xdem-binder
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - jupyter
  - jupytext
  - proj>=7.2
  - fiona
  - shapely
  - numba
  - numpy
  - matplotlib
  - opencv
  - pyproj
  - rasterio
  - scipy
  - tqdm
  - scikit-image
  - proj-data
  - scikit-gstat>=0.6.8
  - pytransform3d

  - pip:
      - git+https://github.com/GlacioHack/geoutils.git
