# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload package to PyPI

on:
  release:
    types: [created]

  workflow_dispatch:
     inputs:
        reason:
          description: 'Reason for manual trigger'
          required: true
          default: 'testing'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools setuptools_scm wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      # Build package, test pip install works, then upload to PyPI with twine
      run: |
        python setup.py sdist bdist_wheel
        pip install dist/*.tar.gz
        twine upload dist/*
